
```{r}
library(tidyverse)
```

```{r}
readxl::read_excel("data/data_excel.xlsx", sheet = "data")

data
```

```{r}
data <- read_delim("data/data_csv.csv", delim = ",")

data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови`  <- factor(data$`Группа крови`)
data
```

```{r}
write_delim(data, "out/data_csv.csv", delim = ",")
list.files("out/")
```

```{r}
read_csv("data/data_csv2.csv")
```

```{r}
openxlsx::write.xlsx(data, "out/data_excel.xlsx")
openxlsx::read.xlsx("out/data_excel.xlsx")
```

```{r}
read_rds("data/data_rds.rds")
write_rds(data, "out/data_rds.rds")
```

```{r}
data$`Группа крови`
data[["Группа крови"]] 
```

```{r}
data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)

data
```

```{r}
data |> select(matches("_E\\d{1}"))
```

```{r}
data |>
  group_by(`Группа`) |>
  filter(`Возраст` > mean(`Возраст`))
```

```{r}
data_1 <- tibble(var_1 = 1:10, var_2 = rep(c("Группа 1", "Группа 2"), 5))
data_2 <- tibble(var_2 = runif(10, 0, 1), var_3 = rnorm(10))
data_3 <- tibble(var_4 = 100:91, var_5 = rep(c("Молодые", "Средний возраст"), 5))
data_1 |>
  bind_cols(data_2) |>
  bind_cols(data_3)
```

```{r}
library(tidyverse)
library(flextable)

data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)

statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)

table <- data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)



table |>
  flextable() |>
  theme_box()
```

```{r}
table |>
    flextable() |>
    theme_box() |>
    merge_v(c("Группа", "Переменная"))
```

```{r}
tibble(var_1 = c("p-value", "0.001"),
       var_2 = c("p-value", "0.05")) |>
    flextable() |>
    theme_box() |>
    merge_h(i=1)
```

```{r}
install.packages(
  c(
    "tidyverse",
    "epiR",
    "Hmisc",
    "lmtest",
    "multcomp",
    "pROC",
    "rstatix",
    "sandwich",
    "TrialSize",
    "yardstick",
    "FactoMineR",
    "factoextra",
    "ggbiplot",
    "dagitty",
    "ggdag",
    "corrplot",
    "ggExtra",
    "GGally",
    "ggfortify",
    "ggpubr",
    "pheatmap",
    "plotly",
    "flextable",
    "openxlsx",
    "gtsummary",
    "devtools",
    "knitr",
    "rmarkdown",
    "styler"
  )
)
```

```{r}
library(ggplot2)
library(dplyr)

beav <- beaver1
beav$id <- 1:nrow(beaver1)
beav <- beav |> mutate(activ = factor(activ))
ggplot(data = beav, aes(x = id, y = temp, group = activ, color = activ)) +
  geom_line() +
  geom_point()
  ```